APP_NAME=Nagad
APP_ENV=local
APP_KEY=base64:3dSUEv10xt5jCIMa6UoPa4+aBI8ZCY00QnJgl3/6QDk=
APP_DEBUG=true
APP_URL=http://localhost:8000

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

# PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=sqlite
# DB_HOST=127.0.0.1
# DB_PORT=3306
# DB_DATABASE=laravel
# DB_USERNAME=root
# DB_PASSWORD=

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_SCHEME=null
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"



NAGAD_BASE_URL="https://api.mynagad.com/api/dfs"
NAGAD_MERCHANT_ID="687481237565399"
NAGAD_ACCOUNT_NUMBER="01748123756"
NAGAD_CALLBACK_URL="${APP_URL}/api/nagad/callback"
NAGAD_PUBLIC_KEY="keys/nagad/nagad_public_key.pem"
NAGAD_PRIVATE_KEY="keys/nagad/nagad_private_key.pem"

NAGAD_API_VERSION="v-0.2.0"
NAGAD_CLIENT_TYPE="PC_WEB"
NAGAD_SERVER_IP="103.112.54.40"
